import type { InterviewLanguage, InterviewMode } from "@/lib/live/types";
import type { DemoScenario } from "@/lib/fixtures/demo-scenario";
import type { StagePersonaSchema, StageQuestionSchema } from "@/lib/gemini/schemas";
import type { z } from "zod";

export interface StageContext {
  title: string;
  focusAreas: string[];
  persona: z.infer<typeof StagePersonaSchema>;
  questionBank: z.infer<typeof StageQuestionSchema>[];
}

interface BuildInterviewerPromptParams {
  mode: InterviewMode;
  language: InterviewLanguage;
  /** specs §5.2 — the demo's fixture CV/JD, passed through so even this
   * generic Phase 1 prompt has real material to probe. */
  scenario?: DemoScenario;
  /** specs §7 — real 'full' mode sessions: the stage's persona and question
   * bank generated by Phase 2's gap analysis, read back from the DB. */
  stageContext?: StageContext;
}

const OPENING: Record<InterviewLanguage, string> = {
  fr: "Tu es un recruteur technique qui mène un entretien d'embauche oral.",
  en: "You are a technical recruiter conducting a live spoken job interview.",
};

const TONE_DIRECTION: Record<StageContext["persona"]["tone"], Record<InterviewLanguage, string>> = {
  warm: { fr: "chaleureux et encourageant", en: "warm and encouraging" },
  neutral: { fr: "neutre et professionnel", en: "neutral and professional" },
  skeptical: { fr: "sceptique et exigeant", en: "skeptical and demanding" },
};

/**
 * Phase 0 walking-skeleton prompt: no roadmap/stage/CV data exists yet
 * (no database in Phase 0), so this is deliberately generic without
 * `scenario` or `stageContext`. Phase 2 adds `scenario` for the demo; Phase 3
 * adds `stageContext` for real authenticated sessions.
 */
export function buildInterviewerPrompt({
  mode,
  language,
  scenario,
  stageContext,
}: BuildInterviewerPromptParams): string {
  const lines = [
    OPENING[language],
    "Ask one question at a time and wait for the candidate's full answer before responding.",
    "Keep your own turns short — this is a conversation, not a monologue.",
    language === "fr"
      ? "Réponds toujours en français."
      : "Always respond in English.",
  ];

  if (mode === "demo") {
    lines.push(
      language === "fr"
        ? "Ceci est une démo de deux minutes : reste sur des questions générales d'entretien."
        : "This is a two-minute demo: stick to general interview questions.",
    );
  }

  if (scenario) {
    lines.push(
      language === "fr"
        ? `Voici le CV du candidat : ${scenario.cvSummary} Voici l'offre visée : ${scenario.jdSummary} Pose au moins une question directe qui sonde un vrai décalage entre le CV et l'offre, sans être diplomate à ce sujet.`
        : `Here is the candidate's CV: ${scenario.cvSummary} Here is the job description: ${scenario.jdSummary} Ask at least one direct question probing a real gap between the CV and the JD — don't be diplomatic about it.`,
    );
  }

  if (stageContext) {
    const { title, focusAreas, persona, questionBank } = stageContext;
    const tone = TONE_DIRECTION[persona.tone][language];

    lines.push(
      language === "fr"
        ? `Cette étape s'appelle "${title}". Adopte le personnage de ${persona.name}, ${persona.role} — ton ton est ${tone} (niveau d'exigence ${persona.strictness}/5). Domaines à évaluer : ${focusAreas.join(", ")}.`
        : `This stage is "${title}". Adopt the persona of ${persona.name}, ${persona.role} — your tone is ${tone} (strictness ${persona.strictness}/5). Areas to assess: ${focusAreas.join(", ")}.`,
    );

    const questionLines = questionBank
      .map((q, i) => `${i + 1}. ${q.text}${q.follow_ups.length ? ` (follow-ups: ${q.follow_ups.join(" / ")})` : ""}`)
      .join("\n");
    lines.push(
      language === "fr"
        ? `Voici ta banque de questions pour cette étape — pose-les dans l'ordre qui te semble naturel, utilise les relances si la réponse est courte ou évasive, et rebondis sur ce que dit le candidat plutôt que de les lire mot pour mot :\n${questionLines}`
        : `Here is your question bank for this stage — ask them in whatever order feels natural, use the follow-ups if an answer is short or evasive, and react to what the candidate actually says rather than reading these verbatim:\n${questionLines}`,
    );
  }

  return lines.join(" ");
}
